# 1. Define the Server
[language-server.svls]
command = "svls"

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = false                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)
snippets_directories = ["~/.config/helix/snippets"]

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"



# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]

# 2. Configure Verilog to use svls
[[language]]
name = "verilog"
scope = "source.verilog"
injection-regex = "verilog"
file-types = ["v", "vh"]
language-servers = ["svls","scls"]
auto-format = true

# 3. Configure SystemVerilog to use svls
[[language]]
name = "systemverilog"
scope = "source.systemverilog"
injection-regex = "systemverilog"
file-types = ["sv", "svh"]
language-servers = ["svls"]
auto-format = true
